"""Opt-in human pane console. Never part of observation storage or forwarding.

The target is an existing pane, including its shell after a foreground job exits.
Only server-generated tmux commands reach a connection bound to that server.
"""
import base64
from contextlib import nullcontext
import hashlib
import hmac
import os
import re
import select
import secrets
import stat
import subprocess
import threading
import time
import unicodedata

from . import collector
from .hub import exact, strict_json


class ConsoleError(ValueError):
    def __init__(self, status, message):
        self.status, self.message = status, message
        super().__init__(message)


def load_policy(path, config):
    fd = os.open(path, os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK)
    with os.fdopen(fd, "rb") as stream:
        info = os.fstat(stream.fileno())
        if not stat.S_ISREG(info.st_mode) or info.st_uid != os.getuid() or info.st_mode & 0o077 or info.st_size > 8192:
            raise ValueError("Console policy must be a private owner-only file")
        data = stream.read(8193)
        if len(data) > 8192:
            raise ValueError("Console policy exceeded the size limit")
    raw = strict_json(data)
    return validate_policy(raw, config)


def validate_policy(raw, config):
    exact(raw, {"identity", "password_sha256", "projects", "allow_input"})
    if not isinstance(raw["identity"], str) or not re.fullmatch(r"[a-zA-Z0-9@._+-]{1,128}", raw["identity"]):
        raise ValueError("Invalid console identity")
    if not isinstance(raw["password_sha256"], str) or not re.fullmatch(r"[a-f0-9]{64}", raw["password_sha256"]):
        raise ValueError("Operator-supplied strong password hash required")
    if (not isinstance(raw["projects"], list) or not raw["projects"] or
            any(not isinstance(p, str) or p not in config["projects"] for p in raw["projects"]) or
            type(raw["allow_input"]) is not bool):
        raise ValueError("Explicit project allowlist and input policy required")
    return raw


def bounded(args, limit=262144):
    # File output is deliberately never used. Bound both runtime and pipe memory.
    process = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
    timer = threading.Timer(3, process.kill)
    timer.start()
    try:
        output = process.stdout.read(limit + 1)
        if len(output) > limit:
            process.kill()
            raise ConsoleError(503, "Pane response exceeded the limit")
        if process.wait(timeout=4):
            raise ConsoleError(409, "Pane unavailable; reconnect explicitly")
        return output.decode("utf-8", errors="replace").rstrip("\n")
    finally:
        timer.cancel()
        if process.poll() is None:
            process.kill()
        process.wait()
        process.stdout.close()


class ControlConnection:
    """A lease-bound client on an existing tmux server; never reconnects.

    The control client ignores sizing and receives no asynchronous pane output.
    Random delimiters prevent pane text from impersonating transaction completion.
    Closing this client does not kill, resize, or detach the user's other clients.
    """
    def __init__(self, command, session):
        if not re.fullmatch(r"\$[0-9]+", session):
            raise ConsoleError(409, "Invalid session identity")
        self.process = subprocess.Popen(command + ["-N", "-C", "attach-session", "-f",
            "no-output,ignore-size", "-t", session], stdin=subprocess.PIPE,
            stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, bufsize=0)
        self.buffer = b""

    def __enter__(self):
        return self

    def __exit__(self, *_args):
        self.process.stdin.close()
        if self.process.poll() is None:
            self.process.terminate()
        try:
            self.process.wait(timeout=1)
        except subprocess.TimeoutExpired:
            self.process.kill()
            self.process.wait()
        self.process.stdout.close()

    def command(self, command):
        marker = "zudo_end_" + secrets.token_hex(32)
        wire = (command + " ; display-message -p " + marker + "\n").encode()
        # Commands are generated by this module. User input is hex bytes only.
        deadline = time.monotonic() + 3
        offset = 0
        os.set_blocking(self.process.stdin.fileno(), False)
        while offset < len(wire):
            remaining = deadline - time.monotonic()
            if remaining <= 0 or not select.select([], [self.process.stdin], [], remaining)[1]:
                raise ConsoleError(503, "Terminal transaction timed out")
            offset += os.write(self.process.stdin.fileno(), wire[offset:])
        output, total, frame = [], 0, None
        while True:
            while b"\n" in self.buffer:
                line, self.buffer = self.buffer.split(b"\n", 1)
                if line == marker.encode():
                    return b"\n".join(output).decode("utf-8", errors="replace")
                if frame is None and line.startswith(b"%begin "):
                    frame = line[7:]
                elif frame is not None and line == b"%end " + frame:
                    frame = None
                elif (frame is not None and line == b"%error " + frame) or (frame is None and line.startswith(b"%exit")):
                    raise ConsoleError(409, "Pane connection failed; reconnect explicitly")
                elif frame is not None:
                    output.append(line)
            remaining = deadline - time.monotonic()
            if remaining <= 0 or not select.select([self.process.stdout], [], [], remaining)[0]:
                raise ConsoleError(503, "Terminal transaction timed out")
            chunk = os.read(self.process.stdout.fileno(), 8192)
            total += len(chunk)
            if not chunk or total > 262144:
                raise ConsoleError(409, "Terminal disconnected or output exceeded the limit")
            self.buffer += chunk


class PaneBackend:
    FORMAT = "#{pid}\t#{session_id}\t#{pane_id}\t#{pane_pid}\t#{pane_dead}\t#{pane_current_path}\t#{pane_current_command}\t#{pane_width}\t#{pane_height}"
    IDENTITY = ("machine", "boot", "server", "pane", "root")

    def __init__(self, config):
        self.config = config
        self.command = ["tmux"] + (["-L", config["tmux_socket"]] if config["tmux_socket"] else [])

    def parse(self, text, projects=True):
        table, boot = collector.processes(), collector.boot_id()
        targets = []
        for line in text.splitlines():
            fields = line.split("\t")
            if len(fields) != 9:
                raise ConsoleError(409, "Invalid pane metadata")
            server_id, session, pane, root_id, dead, cwd, foreground, cols, rows = fields
            if not server_id.isdigit() or not root_id.isdigit() or not re.fullmatch(r"%[0-9]+", pane) or not re.fullmatch(r"\$[0-9]+", session):
                raise ConsoleError(409, "Invalid pane identity")
            server, root = table.get(int(server_id)), table.get(int(root_id))
            if dead != "0" or not server or not root:
                continue
            agent = collector.agent_descendant(int(root_id), table)
            target = dict(project=collector.project_for(cwd, self.config) if projects else None,
                run=collector.run_identity(self.config["machine"], boot, agent) if agent else None,
                machine=self.config["machine"], boot=boot, server=(server["pid"], server["start"]),
                session=session, pane=pane, root=(root["pid"], root["start"]),
                foreground="".join(c for c in foreground if not unicodedata.category(c).startswith("C"))[:128],
                cols=int(cols), rows=int(rows))
            target["id"] = collector.digest(*(target[k] for k in self.IDENTITY))
            targets.append(target)
        return targets

    def connect(self, target):
        channel = ControlConnection(self.command, target["session"])
        try:
            self.validate(target, channel)
        except Exception:
            channel.__exit__()
            raise
        target["_channel"] = channel

    def disconnect(self, target):
        channel = target.pop("_channel", None)
        if channel:
            channel.__exit__()

    def connection(self, target):
        return nullcontext(target["_channel"]) if "_channel" in target else ControlConnection(self.command, target["session"])

    def targets(self):
        return self.parse(bounded(self.command + ["list-panes", "-a", "-F", self.FORMAT]))

    def validate(self, target, channel):
        # Query through the SAME connection used for the operation. Server restart
        # cannot silently reconnect us to a new server or a reused %0 pane.
        current = self.parse(channel.command("list-panes -a -F '" + self.FORMAT + "'"), projects=False)
        matches = [t for t in current if all(t[k] == target[k] for k in self.IDENTITY)]
        if len(matches) != 1:
            raise ConsoleError(409, "Pane replaced or server restarted; reconnect explicitly")
        return matches[0]

    def screen(self, target):
        with self.connection(target) as channel:
            self.validate(target, channel)
            screen = channel.command(f"capture-pane -p -t {target['pane']} -S 0 -E 199")
            current = self.validate(target, channel)
        text = "".join(c for c in screen if c in "\n\t" or not unicodedata.category(c).startswith("C"))
        return dict(screen=text, foreground=current["foreground"], cols=current["cols"], rows=current["rows"])

    def mutate(self, target, commands):
        with self.connection(target) as channel:
            self.validate(target, channel)
            # Same-server pane IDs are not recycled. Respawn replaces pane_pid;
            # check that PID and alive status again inside tmux's command queue.
            condition = "#{&&:#{==:#{pane_pid},%s},#{==:#{pane_dead},0}}" % target["root"][0]
            result = channel.command(f"if-shell -F -t {target['pane']} '{condition}' '{commands} ; display-message -p delivered' 'display-message -p stale'")
            if result != "delivered":
                raise ConsoleError(409, "Pane changed; input was not delivered")
            self.validate(target, channel)

    def send(self, target, text):
        keys = " ".join(f"{byte:02x}" for byte in text.encode("utf-8"))
        self.mutate(target, f"send-keys -t {target['pane']} -H {keys}")

    def resize(self, target, cols, rows):
        self.mutate(target, f"resize-pane -t {target['pane']} -x {cols} -y {rows}")


class Console:
    def __init__(self, config, policy, backend=None, clock=time.monotonic):
        self.policy, self.clock = policy, clock
        self.backend = backend or PaneBackend(config)
        self.machine = config["machine"]
        self.csrf = secrets.token_urlsafe(32)
        self.leases = {}
        self.lock = threading.Lock()

    def release(self, key):
        lease = self.leases.pop(key, None)
        if lease:
            lease["timer"].cancel()
            disconnect = getattr(self.backend, "disconnect", None)
            if disconnect:
                disconnect(lease["target"])

    def expire(self, key):
        with self.lock:
            self.release(key)

    def shutdown(self):
        with self.lock:
            for key in list(self.leases):
                self.release(key)

    def authorized(self, headers):
        values = headers.get_all("Authorization", [])
        if len(values) != 1 or len(values[0]) > 1024 or not values[0].startswith("Basic "):
            return False
        try:
            raw = base64.b64decode(values[0][6:], validate=True).decode("utf-8")
            identity, password = raw.split(":", 1)
        except (ValueError, UnicodeError):
            return False
        return (hmac.compare_digest(identity.encode(), self.policy["identity"].encode()) and
                hmac.compare_digest(hashlib.sha256(password.encode()).hexdigest(), self.policy["password_sha256"]))

    def handle(self, action, body):
        if not self.lock.acquire(blocking=False):
            raise ConsoleError(429, "Console busy; input is never automatically retried")
        try:
            now = self.clock()
            for key in list(self.leases):
                if self.leases[key]["expires"] <= now:
                    self.release(key)
            if action == "targets":
                exact(body, set())
                targets = [t for t in self.backend.targets() if t["project"] in self.policy["projects"]]
                return dict(targets=[{k: t[k] for k in ("project", "run", "machine", "id", "pane", "server", "foreground", "cols", "rows")} for t in targets][:256])
            if action == "open":
                exact(body, {"project", "id", "machine"})
                if any(not isinstance(v, str) or len(v) > 128 for v in body.values()):
                    raise ConsoleError(400, "Invalid target")
                if body["project"] not in self.policy["projects"] or body["machine"] != self.machine:
                    raise ConsoleError(403, "Target is not allowed on this machine")
                matches = [t for t in self.backend.targets() if all(t[k] == body[k] for k in body)]
                if len(matches) != 1:
                    raise ConsoleError(409, "Pane is unavailable or ambiguous")
                if len(self.leases) >= 8:
                    raise ConsoleError(429, "Too many open consoles")
                lease = secrets.token_urlsafe(32)
                target = dict(matches[0])
                connect = getattr(self.backend, "connect", None)
                if connect:
                    connect(target)
                timer = threading.Timer(120, self.expire, args=(lease,))
                timer.daemon = True
                self.leases[lease] = dict(target=target, expires=now + 120, sequence=1, control=False, timer=timer)
                timer.start()
                return dict(lease=lease, expires_in=120, allow_input=self.policy["allow_input"], sequence=1, pane=matches[0]["pane"])
            if action not in {"screen", "close", "control", "send", "resize"}:
                raise ConsoleError(404, "Unknown console operation")
            keys = {"lease"}
            if action == "control": keys |= {"enabled"}
            if action == "send": keys |= {"sequence", "text"}
            if action == "resize": keys |= {"sequence", "cols", "rows"}
            if action in {"send", "resize", "control"} and not self.policy["allow_input"]:
                raise ConsoleError(403, "Control disabled by server policy")
            exact(body, keys)
            if not isinstance(body["lease"], str) or len(body["lease"]) > 128:
                raise ConsoleError(400, "Invalid lease")
            lease = self.leases.get(body["lease"])
            if lease is None:
                raise ConsoleError(409, "Console expired; reconnect explicitly")
            if action == "close":
                self.release(body["lease"])
                return dict(closed=True)
            if action == "control":
                if type(body["enabled"]) is not bool:
                    raise ConsoleError(400, "Explicit control choice required")
                if body["enabled"] and any(other is not lease and other["control"] and other["target"]["id"] == lease["target"]["id"] for other in self.leases.values()):
                    raise ConsoleError(409, "Another connection controls this pane; close it first")
                lease["control"] = body["enabled"]
                return dict(control=lease["control"])
            if action in {"send", "resize"}:
                if not lease["control"]:
                    raise ConsoleError(403, "Enable control for this pane explicitly")
                if type(body["sequence"]) is not int or body["sequence"] != lease["sequence"]:
                    self.release(body["lease"])
                    raise ConsoleError(409, "Duplicate or out-of-order operation; reconnect explicitly")
                if action == "send":
                    if not isinstance(body["text"], str) or not 1 <= len(body["text"].encode("utf-8")) <= 4096:
                        raise ConsoleError(400, "Input must be 1..4096 UTF-8 bytes")
                elif any(type(body[k]) is not int or not low <= body[k] <= high for k, low, high in (("cols", 20, 300), ("rows", 5, 200))):
                    raise ConsoleError(400, "Size must be 20..300 columns and 5..200 rows")
                # Consume before any dispatch. Unknown delivery invalidates the lease;
                # neither an automatic retry nor a reconnect can replay this request.
                lease["sequence"] += 1
                try:
                    if action == "send": self.backend.send(lease["target"], body["text"])
                    else: self.backend.resize(lease["target"], body["cols"], body["rows"])
                except Exception:
                    self.release(body["lease"])
                    raise ConsoleError(409, "Delivery uncertain; do not resend automatically. Reconnect and inspect the pane") from None
                return dict(delivery="sent-to-pane", sequence=lease["sequence"])
            try:
                result = self.backend.screen(lease["target"])
                if lease["expires"] <= self.clock():
                    raise ConsoleError(409, "Console expired; reconnect explicitly")
                return dict(**result, sampled_at=time.time())
            except Exception:
                self.release(body["lease"])
                raise
        finally:
            self.lock.release()
