/* Dashboard-only commands. Terminal input and permissions never enter this registry. */
(()=>{'use strict';
const $=id=>document.getElementById(id), controller=window.WorkspaceController;
const palette=document.createElement('dialog'),help=document.createElement('dialog');
palette.id='command-palette';palette.className='command-dialog';palette.setAttribute('aria-labelledby','command-title');
palette.innerHTML='<div class="command-head"><h2 id="command-title">Commands</h2><button type="button" data-close aria-label="Close commands">×</button></div><label for="command-search">Search commands</label><input id="command-search" type="search" role="combobox" aria-autocomplete="list" aria-controls="command-results" aria-expanded="true" autocomplete="off"><div id="command-results" role="listbox" aria-label="Available commands"></div><p id="command-hint">↑ ↓ to select · Enter to run · Escape to close</p>';
help.id='command-help';help.className='command-dialog';help.setAttribute('aria-labelledby','command-help-title');help.innerHTML='<div class="command-head"><h2 id="command-help-title">Keyboard help</h2><button type="button" data-close aria-label="Close keyboard help">×</button></div><div id="command-help-list"></div><p>Shortcuts work in the dashboard outside text fields and the terminal.</p>';
document.body.append(palette,help);
const search=$('command-search'),results=$('command-results');let selectedId=null,invoker=null,restore=true,composing=false,dispatching=false;
const state=()=>controller.get(),background=()=>!state().inspectorOpen;
const entries=[
 {id:'explorer',label:'Toggle Explorer',aliases:'sidebar tree',category:'Layout',enabled:background,run:()=>controller.setExplorer(!state().explorer)},
 {id:'explorer-show',label:'Show Explorer',aliases:'sidebar tree',category:'Layout',enabled:()=>background()&&!state().explorer,run:()=>controller.setExplorer(true)},
 {id:'overview',label:'Toggle overview',aliases:'summary filters',category:'Layout',enabled:background,run:()=>controller.setOverview(!state().overview)},
 {id:'search',label:'Focus session search',aliases:'find filter',category:'Workspace',enabled:background,run:()=>{controller.focusSearch();return 'destination'}},
 {id:'clear',label:'Clear search and activity filters',aliases:'reset filters',category:'Workspace',enabled:()=>background()&&(!!state().query||state().activity!=='all'||Object.keys(state().scope).length>0),run:()=>controller.clearFilters()},
 {id:'gallery',label:'Gallery view',aliases:'cards',category:'View',enabled:background,run:()=>controller.setView('gallery')},
 {id:'board',label:'Kanban view',aliases:'workflow',category:'View',enabled:background,run:()=>controller.setView('board')},
 ...[['s','Small'],['m','Medium'],['l','Large']].map(([size,label])=>({id:`size-${size}`,label:`${label} thumbnails`,aliases:`size ${size}`,category:'View',enabled:background,run:()=>controller.setSize(size)})),
 {id:'home',label:'All sessions',aliases:'home devices',category:'Navigate',enabled:background,run:()=>{controller.home();$('scope-title').focus({preventScroll:true});return 'destination'}},
 {id:'refresh',label:'Refresh observations',aliases:'reload snapshot',category:'Workspace',enabled:()=>!state().inspectorOpen&&!$('refresh').disabled,run:()=>controller.refresh()},
 {id:'detail-expand',label:'Toggle detail expansion',aliases:'inspector full window',category:'Detail',enabled:()=>state().inspectorOpen,run:()=>controller.setInspectorExpanded(!controller.inspectorExpanded())},
 {id:'settings',label:'Appearance and editor settings',aliases:'preferences',category:'Application',enabled:()=>!$('settings-dialog')?.open,run:source=>{controller.settings(source|| (state().inspectorOpen?$('inspector-commands'):$('commands-open')));return 'destination'}},
 {id:'help',label:'Keyboard help',aliases:'shortcuts question mark',category:'Application',binding:'?',enabled:()=>true,run:()=>{open(help,state().inspectorOpen?$('inspector-help'):$('help-open'));return 'destination'}},
 {id:'commands',label:'Open commands',aliases:'palette',category:'Application',binding:'Mod+K',enabled:()=>true,run:()=>{open(palette,state().inspectorOpen?$('inspector-commands'):$('commands-open'));return 'destination'}}
 ];
function all(){return [...entries,...controller.navigationTargets().map(target=>({id:`navigate:${target.id}`,label:target.label,aliases:`${target.kind} ${target.id}`,category:'Navigate',enabled:background,run:()=>{if(controller.navigateTo(target.id)){const destination=state().inspectorOpen?$('inspector-title'):$('scope-title');destination.focus({preventScroll:true});return 'destination'}}}))]}
function visible(element){if(!element?.isConnected||element.hidden||element.closest('[hidden],[inert]'))return false;const rects=element.getClientRects();return rects.length>0&&getComputedStyle(element).visibility!=='hidden'}
function fallback(){return state().inspectorOpen?$('inspector-commands'):$('commands-open')}
function close(dialog,keepFocus=false){if(!dialog.open)return;dialog.close();if(keepFocus)return;const target=visible(invoker)?invoker:fallback();if(visible(target))target.focus({preventScroll:true})}
function open(dialog,from){if(composing||$('settings-dialog')?.open)return false;const other=dialog===palette?help:palette;if(other.open)close(other,true);invoker=from||document.activeElement;restore=true;if(dialog===palette){search.value='';selectedId=null;render()}else renderHelp();if(!dialog.open)dialog.showModal();(dialog===palette?search:dialog.querySelector('[data-close]')).focus({preventScroll:true});return true}
function render(){const terms=search.value.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);const items=all().filter(item=>terms.every(term=>`${item.label} ${item.aliases} ${item.category}`.toLocaleLowerCase().includes(term)));const available=items.filter(item=>item.enabled());if(!available.some(item=>item.id===selectedId))selectedId=available[0]?.id||null;results.replaceChildren();for(const item of items){const row=document.createElement('button');row.type='button';row.tabIndex=-1;row.id=`command-option-${results.childElementCount}`;row.className='command-result';row.setAttribute('role','option');row.dataset.commandId=item.id;row.setAttribute('aria-selected',String(item.id===selectedId));row.disabled=!item.enabled();const main=document.createElement('span'),label=document.createElement('strong'),category=document.createElement('small');label.textContent=item.label;category.textContent=item.category;main.append(label,category);row.append(main);if(item.binding){const key=document.createElement('kbd');key.textContent=item.binding;row.append(key)}results.append(row);if(item.id===selectedId)search.setAttribute('aria-activedescendant',row.id)}if(!selectedId)search.removeAttribute('aria-activedescendant');if(!items.length){const empty=document.createElement('p');empty.textContent='No matching commands';results.append(empty)}}
function renderHelp(){const host=$('command-help-list');host.replaceChildren();for(const item of entries.filter(item=>item.binding)){const row=document.createElement('div'),name=document.createElement('span'),key=document.createElement('kbd');row.className='command-help-row';name.textContent=item.label;key.textContent=item.binding;row.append(name,key);host.append(row)}}
function execute(id,source){if(dispatching)return false;const item=all().find(entry=>entry.id===id);if(!item||!item.enabled()) {if(palette.open)render();return false}dispatching=true;const fromDialog=palette.open||help.open;try{if(palette.open)close(palette,true);if(help.open)close(help,true);const outcome=item.run(source);if(fromDialog&&outcome!=='destination'){const target=visible(invoker)?invoker:fallback();if(visible(target))target.focus({preventScroll:true})}return true}finally{dispatching=false}}
function moveSelection(delta){const ids=[...results.querySelectorAll('[data-command-id]:not(:disabled)')].map(row=>row.dataset.commandId);if(!ids.length)return;const index=ids.indexOf(selectedId);selectedId=ids[(index+delta+ids.length)%ids.length];render();results.querySelector('[aria-selected="true"]')?.scrollIntoView({block:'nearest'})}
search.addEventListener('input',render);results.addEventListener('pointermove',event=>{const row=event.target.closest('[data-command-id]:not(:disabled)');if(row&&selectedId!==row.dataset.commandId){selectedId=row.dataset.commandId;for(const option of results.querySelectorAll('[data-command-id]'))option.setAttribute('aria-selected',String(option.dataset.commandId===selectedId));search.setAttribute('aria-activedescendant',row.id)}});results.addEventListener('click',event=>{const row=event.target.closest('[data-command-id]:not(:disabled)');if(row)execute(row.dataset.commandId)});
for(const dialog of [palette,help]){dialog.querySelector('[data-close]').onclick=()=>close(dialog);dialog.addEventListener('compositionstart',()=>{composing=true});dialog.addEventListener('compositionend',()=>{composing=false});dialog.addEventListener('cancel',event=>{event.preventDefault();event.stopPropagation();if(!composing)close(dialog)});dialog.addEventListener('keydown',event=>{if(event.key==='Escape'){event.stopPropagation();event.preventDefault();if(!composing&&!event.isComposing&&event.keyCode!==229)close(dialog)}else if(dialog===palette&&(event.target===search||results.contains(event.target))&&['ArrowDown','ArrowUp','Enter'].includes(event.key)){if(composing||event.isComposing||event.keyCode===229||event.repeat||event.defaultPrevented)return;event.preventDefault();event.stopPropagation();if(event.key==='Enter')execute(selectedId);else moveSelection(event.key==='ArrowDown'?1:-1)}})}
function shortcut(event){if(event.defaultPrevented||event.repeat||event.isComposing||composing||event.keyCode===229)return null;const mac=/Mac|iPhone|iPad/.test(navigator.platform);if(event.key.toLowerCase()==='k'&&!event.getModifierState?.('AltGraph')&&(mac?event.metaKey&&!event.ctrlKey:event.ctrlKey&&!event.metaKey)&&!event.altKey&&!event.shiftKey)return 'commands';if(event.key==='?'&&!event.ctrlKey&&!event.metaKey&&!event.altKey&&!event.getModifierState?.('AltGraph'))return 'help';return null}
function editable(target){return !!target?.closest?.('input,textarea,select,[contenteditable],.cm-editor,.cm-content,.cm-vimMode,[role="textbox"],iframe')}
document.addEventListener('keydown',event=>{const id=shortcut(event);if(!id||editable(event.target)||$('settings-dialog')?.open||palette.open||help.open)return;event.preventDefault();open(id==='commands'?palette:help,document.activeElement)});
$('commands-open').onclick=event=>open(palette,event.currentTarget);$('help-open').onclick=event=>open(help,event.currentTarget);$('inspector-commands').onclick=event=>open(palette,event.currentTarget);$('inspector-help').onclick=event=>open(help,event.currentTarget);
window.addEventListener('dashboard-commands-context',()=>{if(state().inspectorOpen===false&&(palette.open||help.open)&&invoker?.closest?.('#inspector')){close(palette,true);close(help,true);fallback()?.focus({preventScroll:true})}else if(palette.open)render()});
window.DashboardCommands={execute,closeForSettings:()=>{close(palette,true);close(help,true)},openPalette:from=>open(palette,from),openHelp:from=>open(help,from),closeForInspector:()=>{close(palette,true);close(help,true)},registry:all,shortcut};
})();
