/* Only whitelisted appearance/editor preferences are stored in this browser. */
(()=>{'use strict';
const defaults={theme:'system',vim:false,wrap:true,lineNumbers:false,fontSize:14};
const key='zudo-agent-dashboard-settings-v1',media=window.matchMedia('(prefers-color-scheme: dark)');
function clean(value){return {theme:['system','light','dark'].includes(value?.theme)?value.theme:'system',vim:value?.vim===true,wrap:value?.wrap!==false,lineNumbers:value?.lineNumbers===true,fontSize:[13,14,16,18].includes(Number(value?.fontSize))?Number(value.fontSize):14}}
let settings=defaults;try{settings=clean(JSON.parse(localStorage.getItem(key))||defaults)}catch{}
function apply(){document.documentElement.dataset.theme=settings.theme;document.documentElement.dataset.colorMode=settings.theme==='system'?(media.matches?'dark':'light'):settings.theme;window.dispatchEvent(new CustomEvent('dashboard-preferences',{detail:{...settings}}))}
function receive(value){const next=clean(value),changed=JSON.stringify(next)!==JSON.stringify(settings);settings=next;apply();if(window.parent===window&&changed)for(const frame of document.querySelectorAll('iframe')){try{frame.contentWindow?.ThemeSettings?.receive(next)}catch{}}}
function commit(value){receive(value);try{localStorage.setItem(key,JSON.stringify(settings))}catch{}if(parent!==window){try{parent.ThemeSettings?.receive(settings)}catch{}}}
window.ThemeSettings={get:()=>({...settings}),receive,commit,effective:()=>document.documentElement.dataset.colorMode};
/* Layout preferences are separate from editor/appearance settings and safe to apply before paint. */
const workspaceKey='zudo-agent-dashboard-workspace-v1';
const workspaceDefaults={explorer:false,overview:false,view:'board'};
function cleanWorkspace(value){return {explorer:value?.explorer===true,overview:value?.overview===true,view:['board','gallery'].includes(value?.view)?value.view:'board'}}
let workspace=workspaceDefaults;try{workspace=cleanWorkspace(JSON.parse(localStorage.getItem(workspaceKey)))}catch{}
function applyWorkspace(){const root=document.documentElement;root.dataset.workspaceExplorer=String(workspace.explorer);root.dataset.workspaceOverview=String(workspace.overview);root.dataset.workspaceView=workspace.view;window.dispatchEvent(new CustomEvent('dashboard-workspace-preferences',{detail:{...workspace}}))}
function receiveWorkspace(value){workspace=cleanWorkspace(value);applyWorkspace()}
function commitWorkspace(value){receiveWorkspace({...workspace,...value});try{localStorage.setItem(workspaceKey,JSON.stringify(workspace))}catch{}}
window.WorkspacePreferences={get:()=>({...workspace}),commit:commitWorkspace,receive:receiveWorkspace};
window.addEventListener('storage',event=>{if(event.key===workspaceKey){try{receiveWorkspace(JSON.parse(event.newValue))}catch{receiveWorkspace(workspaceDefaults)}}});applyWorkspace();

media.addEventListener('change',()=>{if(settings.theme==='system')apply()});window.addEventListener('storage',event=>{if(event.key===key){try{receive(JSON.parse(event.newValue)||defaults)}catch{}}});apply();
function setup(){
const dialog=document.createElement('dialog');dialog.id='settings-dialog';dialog.className='settings-dialog';dialog.setAttribute('aria-labelledby','settings-title');dialog.innerHTML=`<form method="dialog"><div class="settings-heading"><div><span class="settings-eyebrow">PREFERENCES</span><h2 id="settings-title">Appearance & editor</h2></div><button type="button" data-cancel aria-label="Cancel settings" class="settings-close">×</button></div><p class="settings-intro">For this browser. Changes take effect when you apply.</p><fieldset><legend>Appearance</legend><label class="settings-row"><span>Theme<small>System follows your device</small></span><select name="theme"><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label></fieldset><fieldset><legend>Compose editor</legend><label class="settings-row"><span>Vim keybindings<small>Normal, Insert and Visual modes</small></span><input type="checkbox" name="vim"></label><label class="settings-row"><span>Wrap long lines</span><input type="checkbox" name="wrap"></label><label class="settings-row"><span>Line numbers</span><input type="checkbox" name="lineNumbers"></label><label class="settings-row"><span>Text size</span><select name="fontSize"><option value="13">13 px</option><option value="14">14 px</option><option value="16">16 px</option><option value="18">18 px</option></select></label></fieldset><p class="settings-note">Vim applies only to Compose. Enter writes a new line. Sending is always an explicit button action. Direct input keeps terminal key behavior.</p><div class="settings-actions"><button type="button" data-cancel>Cancel</button><button type="submit" class="settings-apply">Apply settings</button></div></form>`;
document.body.append(dialog);let returnTo=null,composing=false;dialog.addEventListener('compositionstart',()=>{composing=true});dialog.addEventListener('compositionend',()=>{composing=false});
function cancel(){dialog.close();returnTo?.focus?.({preventScroll:true})}
function open(button){if(window.consoleLayout?.isComposing?.())return;window.DashboardCommands?.closeForSettings?.();returnTo=button||document.activeElement;const saved=window.ThemeSettings.get();for(const [name,value] of Object.entries(saved)){const field=dialog.querySelector(`[name="${name}"]`);if(field.type==='checkbox')field.checked=value;else field.value=String(value)}dialog.showModal();dialog.querySelector('[name="theme"]').focus()}
dialog.querySelectorAll('[data-cancel]').forEach(button=>button.onclick=cancel);dialog.addEventListener('cancel',event=>{event.preventDefault();event.stopPropagation();if(!composing)cancel()});dialog.addEventListener('keydown',event=>{if(event.key==='Escape'){event.stopPropagation();if(composing||event.isComposing||event.keyCode===229){event.preventDefault();return}event.preventDefault();cancel()}});dialog.querySelector('form').onsubmit=event=>{event.preventDefault();const next={};for(const name of Object.keys(defaults)){const field=dialog.querySelector(`[name="${name}"]`);next[name]=field.type==='checkbox'?field.checked:field.value}commit(next);cancel()};document.addEventListener('click',event=>{const button=event.target.closest('[data-open-settings]');if(button)(window.DashboardCommands?.execute('settings',button)??open(button))});window.ThemeSettings.open=open;
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup,{once:true});else setup();
})();
