'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const {JSDOM} = require('jsdom');

const html = '<!doctype html><html><head><meta name="csp-nonce" content="test-nonce"></head><body><button data-open-settings>Settings</button><span id="editor-mode"></span><div id="host"></div></body></html>';
const dom = new JSDOM(html, {url:'http://localhost/', runScripts:'outside-only', pretendToBeVisual:true});
const {window} = dom;
window.matchMedia = () => ({matches:false, addEventListener(){}, removeEventListener(){}});
window.ResizeObserver = class {observe(){} unobserve(){} disconnect(){}};
window.requestAnimationFrame = callback => setTimeout(callback,0);
window.cancelAnimationFrame = clearTimeout;
window.scrollTo = () => {};
window.HTMLElement.prototype.getClientRects = function(){return []};
window.HTMLElement.prototype.scrollIntoView = function(){};
window.document.elementFromPoint = () => window.document.body;
window.document.execCommand = () => true;
window.HTMLDialogElement.prototype.showModal = function(){this.open=true};
window.HTMLDialogElement.prototype.close = function(){this.open=false};
window.eval(fs.readFileSync('zudo_agent/web/preferences.js','utf8'));
window.document.dispatchEvent(new window.Event('DOMContentLoaded'));
window.eval(fs.readFileSync('zudo_agent/web/editor.js','utf8'));
const host = window.document.getElementById('host');
const editor = window.createComposerEditor(host);
assert.equal(editor.state().viewCount,1);
assert.equal(window.document.querySelector('style')?.nonce,'test-nonce');
assert.equal(editor.state().enabled,false);
editor.setEnabled(true);
editor.selectPane('one');
editor.value = 'first\nline';
editor.setSelectionRange(2,5);
assert.equal(editor.selectionStart,2);
assert.equal(editor.selectionEnd,5);
const geometry=editor.snapshot();
editor.setSelectionRange(0,0);
editor.restore(geometry);
assert.equal(editor.selectionStart,2);
editor.selectPane('two');
assert.equal(editor.value,'');
editor.value='second';
editor.selectPane('one');
assert.equal(editor.value,'first\nline');
assert.equal(editor.selectionStart,2);
assert.equal(editor.selectionEnd,5);
assert.equal(editor.state().viewCount,1);
assert.equal(editor.undo(),true);
assert.equal(editor.value,'');
assert.equal(editor.redo(),true);
assert.equal(editor.value,'first\nline');
const settingsButton=window.document.querySelector('[data-open-settings]');
window.ThemeSettings.open(settingsButton);
const dialog=window.document.getElementById('settings-dialog');
assert.equal(dialog.open,true);
dialog.querySelector('[name="vim"]').checked=true;
dialog.querySelector('[data-cancel]').click();
assert.equal(window.ThemeSettings.get().vim,false);
window.ThemeSettings.open(settingsButton);
assert.equal(dialog.querySelector('[name="vim"]').checked,false);
dialog.querySelector('[name="theme"]').value='dark';
dialog.querySelector('[name="vim"]').checked=true;
dialog.querySelector('form').dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));
assert.equal(window.ThemeSettings.effective(),'dark');
assert.equal(editor.state().vim,true);
assert.equal(editor.value,'first\nline');
assert.equal(editor.state().viewCount,1);
editor.vimKey('i');
assert.equal(editor.state().vimMode,'insert');
editor.vimKey('<Esc>');
editor.vimKey('g'); editor.vimKey('g'); editor.vimKey('y'); editor.vimKey('y');
editor.selectPane('register-proof'); editor.vimKey('p');
assert.match(editor.value,/first/, 'fixture actually populated a Vim register');
editor.reset();
assert.equal(editor.undo(),false, 'disconnect clears undo history');
assert.equal(editor.value,'');
assert.equal(editor.state().pane,'');
assert.equal(editor.state().vimMode,'normal');
editor.setEnabled(true); editor.selectPane('fresh-session'); editor.vimKey('p');
assert.equal(editor.value,'', 'Vim register cannot restore previous-session draft');
editor.destroy();
assert.equal(host.querySelector('.cm-editor'),null);
assert.equal(window.composerEditor,undefined);
console.log('editor: state, per-pane history, settings, reset, teardown passed');
