import {EditorState, Compartment, Transaction} from '@codemirror/state';
import {EditorView, keymap, drawSelection, highlightActiveLine, lineNumbers, placeholder} from '@codemirror/view';
import {defaultKeymap, history, historyKeymap, undo, redo, undoDepth} from '@codemirror/commands';
import {vim, getCM, Vim} from '@replit/codemirror-vim';
// One actual EditorView. Expanding and themes only reconfigure it; no cloned textarea.
window.createComposerEditor=(host,callbacks={})=>{
 const modes=new Compartment(),appearance=new Compartment(),wrapping=new Compartment(),numbers=new Compartment(),editable=new Compartment(),label=new Compartment();
 let prefs=window.ThemeSettings.get(),enabled=false,paneId='',pendingPrefs=null;
 const states=new Map(),scrollPositions=new Map();
 const theme=()=>EditorView.theme({'&':{height:'100%',fontSize:prefs.fontSize+'px',color:'var(--text)',backgroundColor:'var(--editor-bg)'},'.cm-scroller':{fontFamily:'ui-monospace,SFMono-Regular,Consolas,monospace',overflow:'auto',lineHeight:'1.6'},'.cm-content':{padding:'10px 0',caretColor:'var(--text)'},'.cm-line':{padding:'0 12px'},'.cm-gutters':{backgroundColor:'var(--surface)',color:'var(--muted)',borderColor:'var(--border)'},'.cm-activeLine,.cm-activeLineGutter':{backgroundColor:'var(--hover)'},'&.cm-focused':{outline:'none'},'&.cm-focused .cm-selectionBackground,.cm-selectionBackground,::selection':{backgroundColor:'var(--selection)'},'.cm-cursor,.cm-dropCursor':{borderLeftColor:'var(--text)'},'.cm-fat-cursor':{background:'var(--text)',color:'var(--editor-bg)'},'.cm-panels':{backgroundColor:'var(--surface)',color:'var(--text)'},'.cm-panel input':{color:'var(--text)',background:'var(--editor-bg)'}},{dark:window.ThemeSettings.effective()==='dark'});
 const status=()=>{const cm=getCM(view),state=cm?.state?.vim;const mode=!prefs.vim?'Text':state?.insertMode?'INSERT':state?.visualMode?'VISUAL':'NORMAL';document.getElementById('editor-mode').textContent=prefs.vim?'Vim · '+mode:'CodeMirror';document.getElementById('editor-mode').dataset.mode=mode.toLowerCase()};
 const extensions=()=>[modes.of(prefs.vim?vim({status:true}):[]),history(),drawSelection(),highlightActiveLine(),keymap.of([...defaultKeymap,...historyKeymap]),wrapping.of(prefs.wrap?EditorView.lineWrapping:[]),numbers.of(prefs.lineNumbers?lineNumbers():[]),appearance.of(theme()),editable.of([EditorState.readOnly.of(!enabled),EditorView.editable.of(enabled)]),label.of(EditorView.contentAttributes.of({'aria-label':'Compose draft. Enter writes a new line; use Send to submit.','spellcheck':'false'})),placeholder('Write an instruction…'),EditorView.updateListener.of(update=>{if(update.docChanged||update.selectionSet)callbacks.change?.();status()}),EditorView.domEventHandlers({compositionstart:()=>{callbacks.composition?.(true);return false},compositionend:()=>{callbacks.composition?.(false);if(pendingPrefs){const next=pendingPrefs;pendingPrefs=null;setTimeout(()=>configure(next),0)}return false},keydown:event=>{if(event.key==='Escape'&&prefs.vim){event.stopPropagation()}return false}})];
 const view=new EditorView({state:EditorState.create({doc:'',extensions:extensions()}),parent:host});
 // Bubble only: Vim's own handler sees Escape first. Normal-mode Escape never escapes the editor.
 view.dom.addEventListener('keydown',event=>{if(event.key==='Escape'&&(prefs.vim||document.body.classList.contains('composer-expanded')))event.stopPropagation();setTimeout(status,0)});
 function configure(next,force=false){if(view.composing){pendingPrefs=next;return}const prior=prefs;prefs=next;const top=view.scrollDOM.scrollTop,left=view.scrollDOM.scrollLeft;view.dispatch({effects:[...((force||prior.vim!==prefs.vim)?[modes.reconfigure(prefs.vim?vim({status:true}):[])]:[]),appearance.reconfigure(theme()),wrapping.reconfigure(prefs.wrap?EditorView.lineWrapping:[]),numbers.reconfigure(prefs.lineNumbers?lineNumbers():[])]});view.scrollDOM.scrollTop=top;view.scrollDOM.scrollLeft=left;status()}
 window.addEventListener('dashboard-preferences',event=>configure(event.detail));
 const api={view,get value(){return view.state.doc.toString()},set value(text){if(text===this.value)return;view.dispatch({changes:{from:0,to:view.state.doc.length,insert:String(text)}})},get selectionStart(){return view.state.selection.main.from},get selectionEnd(){return view.state.selection.main.to},get selectionDirection(){return view.state.selection.main.anchor>view.state.selection.main.head?'backward':'forward'},setSelectionRange(start,end,direction){const max=view.state.doc.length;view.dispatch({selection:{anchor:Math.min(max,direction==='backward'?end:start),head:Math.min(max,direction==='backward'?start:end)}})},setEnabled(next){enabled=Boolean(next);view.dispatch({effects:editable.reconfigure([EditorState.readOnly.of(!enabled),EditorView.editable.of(enabled)])})},focus(){if(enabled)view.focus()},hasFocus:()=>view.hasFocus,get composing(){return view.composing},setLabel(text){view.dispatch({effects:label.reconfigure(EditorView.contentAttributes.of({'aria-label':text,'spellcheck':'false'}))})},selectPane(id){if(id===paneId)return;if(paneId){states.set(paneId,view.state);scrollPositions.set(paneId,{top:view.scrollDOM.scrollTop,left:view.scrollDOM.scrollLeft})}paneId=id;view.setState(states.get(id)||EditorState.create({doc:'',extensions:extensions()}));view.dispatch({effects:editable.reconfigure([EditorState.readOnly.of(!enabled),EditorView.editable.of(enabled)])});configure(prefs,true);const at=scrollPositions.get(id)||{top:0,left:0};view.scrollDOM.scrollTop=at.top;view.scrollDOM.scrollLeft=at.left},measure(){view.requestMeasure()},snapshot:()=>({top:view.scrollDOM.scrollTop,left:view.scrollDOM.scrollLeft,selection:view.state.selection,focused:view.hasFocus}),restore(snapshot){view.requestMeasure();requestAnimationFrame(()=>{view.scrollDOM.scrollTop=snapshot.top;view.scrollDOM.scrollLeft=snapshot.left;if(snapshot.focused&&enabled&&!view.composing)view.focus()})},undo:()=>undo(view),redo:()=>redo(view),vimKey:key=>{const cm=getCM(view);if(cm&&enabled){Vim.handleKey(cm,key);status()}},state:()=>({pane:paneId,enabled,vim:prefs.vim,vimMode:!prefs.vim?'text':getCM(view)?.state?.vim?.insertMode?'insert':getCM(view)?.state?.vim?.visualMode?'visual':'normal',doc:view.state.doc.toString(),selection:view.state.selection.toJSON(),undoDepth:undoDepth(view.state),viewCount:host.querySelectorAll('.cm-editor').length})};status();window.composerEditor=api;return api;
};
